limon_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import urls
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('pages/', include('pages.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('articles.urls')),

]

# urlpatterns += i18n_patterns(path('', include('articles.urls')), prefix_default_language=False,)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import ContactPageView


urlpatterns = [
    #страница контактов
    path('contacts/', ContactPageView.as_view(), name='contacts'),
]
#http://localhost:8000/

articles/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from datetime import datetime
from django.urls import reverse
from tinymce.models import HTMLField




class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        

class Article(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=255)
    description = HTMLField()
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='article-photos/', default='media/default.jpg')
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE,
    )
    # updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', args=[str(self.id)])
    
    @property
    def get_absolute_image_url(self):
        return f'{self.image.url}'

    class Meta:
        ordering =('-date', )


class Comment(models.Model):
    """Комментарии"""
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField(max_length=255)
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE
    )
    date = models.DateTimeField(auto_now_add=datetime.now())
    reply = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, related_name='replies')    
    def __str__(self):
        return self.comment[:50]
    
    def get_absolute_url(self):
        return reverse('article_list')
     
    class Meta:
        ordering = ('author', )


class ArticleViews(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_statistic')
    date = models.DateTimeField(auto_now_add=datetime.now())
    views = models.IntegerField('Views', default=0)

    def __str__(self):
        return self.article.title

    

templates/base.html
{% load category_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} Limon kg {% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Logo-Limon</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Posts</a>
        </li>
        <li class="nav-item dropdown">
          {% if user.is_authenticated %}
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Профиль {{user.username}}
          </a>
          {% else %}
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Войти
          </a>
          {% endif %}
          {% if user.is_authenticated %}
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
            <a class="dropdown-item" href="{% url 'profile' {{user.id}} %}">Перейти в Профиль</a>
            <a class="dropdown-item" href="{% url 'password_change' %}">Поменять пароль</a>
            <a class="dropdown-item" href="{% url 'password_reset' %}">Сбросить пароль</a>
            <a class="dropdown-item" href="{% url 'article_new' %}">Создать статью</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Мои посты</a>
          </div>
          {% else %}
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'login' %}">Войти</a>
            <a class="dropdown-item" href="{% url 'signup' %}">Зарегистрироваться</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Перейти в посты</a>
          </div>
          {% endif %}
        </li>



        <!-- category -->


        <!-- endcategory -->

        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form action="" method="GET">
        <div class="form-group">
          <label for="exampleFormControlSelect1" style="color:white;">Категории </label>
          {% get_all_categories as categories  %}
          <select multiple class="form-control" name="category" id="exampleFormControlSelect1">
            <option> Выберите категорию </option>
            {% for category in categories %}
            <option value="{{category.id}}">{{category.name}}</option>
            {% endfor %}
          </select>
        </div>
        <button type="submit"> Фильтр </button>
      </form>
      <form class="form-inline my-2 my-lg-0" method="GET">
        <input class="form-control mr-sm-2" type="search" name="search_title" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    У страницы нет данных
    {% endblock %}

  </div>

</body>

</html>

templates/category.html
{% extends 'new_base.html' %}

{% block content  %}
<!-- Start banner Area -->
<section class="banner-area relative">
	<div class="overlay overlay-bg"></div>
	<div class="container box_1170">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					Category Page
				</h1>
				<p class="text-white link-nav"><a href="index.html">Home </a> <span class="lnr lnr-arrow-right"></span>
					<a href="category.html">
						Category</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start main body Area -->
<div class="main-body section-gap">
	<div class="container box_1170">
		<div class="row">
			<div class="col-lg-8 post-list">
				<!-- Start Post Area -->
				<section class="post-area">
					<div class="row">
						{% for category in categories %}
						<div class="col-lg-6 col-md-6">
							<div class="single-post-item">
								<div class="post-thumb">
									<img class="img-fluid" src="img/archive/c1.jpg" alt="">
								</div>
								<div class="post-details">
									<h4><a href="#">{{category.name}}</a></h4>
									<p>Some data</p>
									<div class="blog-meta">
										<a href="#" class="m-gap"><span
												class="lnr lnr-calendar-full"></span>{{category.date}}</a>
										<a href="#" class="m-gap"><span
												class="lnr lnr-bubble"></span>{{category.article_set.count}}</span></a>
									</div>
								</div>
							</div>
						</div>
						{% endfor  %}
						<div class="col-lg-12">
							<nav class="blog-pagination justify-content-center d-flex">
								<ul class="pagination">
									<li class="page-item">
										<a href="#" class="page-link" aria-label="Previous">
											<span aria-hidden="true">
												<span class="lnr lnr-arrow-left"></span>
											</span>
										</a>
									</li>
									<li class="page-item"><a href="#" class="page-link">01</a></li>
									<li class="page-item active"><a href="#" class="page-link">02</a></li>
									<li class="page-item"><a href="#" class="page-link">03</a></li>
									<li class="page-item"><a href="#" class="page-link">04</a></li>
									<li class="page-item"><a href="#" class="page-link">09</a></li>
									<li class="page-item">
										<a href="#" class="page-link" aria-label="Next">
											<span aria-hidden="true">
												<span class="lnr lnr-arrow-right"></span>
											</span>
										</a>
									</li>
								</ul>
							</nav>
						</div>
					</div>
				</section>
				<!-- Start Post Area -->
			</div>


			<div class="col-lg-4 sidebar">
				{% include 'includes/popular_article_author.html' %}

				{% include 'includes/popular_and_latest.html' %}

				{% include 'includes/post_categories.html' %}

				{% include 'includes/post_tags.html' %}

			</div>
		</div>
	</div>
</div>
<!-- Start main body Area -->

{% endblock content %}

templates/contact.html
{% extends 'new_base.html' %}
{% load static %}
{% block content %}
	<!-- Start banner Area -->
	<section class="banner-area relative">
		<div class="overlay overlay-bg"></div>
		<div class="container box_1170">
			<div class="row d-flex align-items-center justify-content-center">
				<div class="about-content col-lg-12">
					<h1 class="text-white">
						Post Archive
					</h1>
					<p class="text-white link-nav"><a href="{% url 'article_list' %}">Home </a> <span class="lnr lnr-arrow-right"></span> <a href="{% url 'categories' %}">
							Archive</a></p>
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->

	<!-- Start contact-page Area -->
	<section class="contact-page-area section-gap">
		<div class="container box_1170">
			<div class="row">
				<div class="map-wrap" style="width:100%; height: 445px;" id="map"></div>
				<div class="col-lg-4 d-flex flex-column address-wrap">
					<div class="single-contact-address d-flex flex-row">
						<div class="icon">
							<span class="lnr lnr-home"></span>
						</div>
						<div class="contact-details">
							<h5>Dhaka, Bangladesh</h5>
							<p>56/8, West Panthapath</p>
						</div>
					</div>
					<div class="single-contact-address d-flex flex-row">
						<div class="icon">
							<span class="lnr lnr-phone-handset"></span>
						</div>
						<div class="contact-details">
							<h5>00 (880) 9865 562</h5>
							<p>Mon to Fri 9am to 6 pm</p>
						</div>
					</div>
					<div class="single-contact-address d-flex flex-row">
						<div class="icon">
							<span class="lnr lnr-envelope"></span>
						</div>
						<div class="contact-details">
							<h5>support@codethemes.com</h5>
							<p>Send us your query anytime!</p>
						</div>
					</div>
				</div>
				<div class="col-lg-8">
					<form class="form-area " id="myForm" action="mail.php" method="post" class="contact-form text-right">
						<div class="row">
							<div class="col-lg-6 form-group">
								<input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'"
								 class="common-input mb-20 form-control" required="" type="text">

								<input name="email" placeholder="Enter email address" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
								 onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" class="common-input mb-20 form-control"
								 required="" type="email">

								<input name="subject" placeholder="Enter your subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your subject'"
								 class="common-input mb-20 form-control" required="" type="text">
							</div>
							<div class="col-lg-6 form-group">
								<textarea class="common-textarea form-control" name="message" placeholder="Messege" onfocus="this.placeholder = ''"
								 onblur="this.placeholder = 'Messege'" required=""></textarea>
							</div>
							<div class="col-lg-12 d-flex justify-content-between">
								<div class="alert-msg" style="text-align: left;"></div>
								<button class="genric-btn primary circle text-uppercase" style="float: right;">Send Message</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
	<!-- End contact-page Area -->

	{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block title %} Index Page of Limon {% endblock %}

{% block content %}

<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'article_list' %}" role="button">View All Articles »</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
        </div>
      </div>

      <hr>

    </div> <!-- /container -->

  </main>
  
  {% endblock %}

templates/index1.html
{% extends 'new_base.html' %}
{% load static %}
{% load latest_posts %}
{% block content %}
	<!-- Top Stories Area -->
	<section class="top-stories-area">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="owl-carousel active-stories-carousel">
						<!-- single stories carousel -->
						{% get_latest_posts as latest_posts %}
						{% for latest_post in latest_posts %}
						<div class="single-stories-carousel d-flex align-items-center">
							<div class="stories-thumb">
								<img width="50" class="img-fluid" src="{{latest_post.get_absolute_image_url}}" alt="">
							</div>
							<div class="stories-details">
								<h6><a href="{{latest_post.get_absolute_url}}">{{latest_post.title}}<br></a></h6>
								<p>{{latest_post.date}}</p>
	
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Stories Area -->

	<!-- Start Post Silder Area -->
	<section class="post-slider-area">
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-lg-12">
					<div class="owl-carousel active-post-carusel">
						<!-- single carousel item -->
						<div class="single-post-carousel">
							<div class="post-thumb">
								<img class="img-fluid" src="{% static 'img/posts/carousel/post1.jpg' %}" alt="">
							</div>
							<div class="post-details">
								<h2><a href="#">2nd Gen Smoke Alarm get up <br>
										from sleep Daily</a></h2>
								<div class="post-content d-flex justify-content-between">
									<div class="post-meta">
										<div class="thumb"><img src="{% static 'img/author/a1.png' %}" alt=""></div>
										<div class="c-desc">
											<h6>Marvel Maison</h6>
											<p><span class="lnr lnr-calendar-full"></span>13th Oct, 2018</p>
										</div>
									</div>
									<div class="details">
										<p>There is a moment in the life of any aspiring astronomer that it is time to buy that first telescope.
											It’s exciting to think about setting up your own viewing station.</p>
									</div>
								</div>
							</div>
						</div>
						<!-- single carousel item -->
						<div class="single-post-carousel">
							<div class="post-thumb">
								<img class="img-fluid" src="{% static 'img/posts/carousel/post2.jpg' %}" alt="">
							</div>
							<div class="post-details">
								<h2><a href="#">2nd Gen Smoke Alarm get up <br>
										from sleep Daily</a></h2>
								<div class="post-content d-flex justify-content-between">
									<div class="post-meta">
										<div class="thumb"><img src="{% static 'img/author/a1.png' %}" alt=""></div>
										<div class="c-desc">
											<h6>Marvel Maison</h6>
											<p><span class="lnr lnr-calendar-full"></span>13th Oct, 2018</p>
										</div>
									</div>
									<div class="details">
										<p>There is a moment in the life of any aspiring astronomer that it is time to buy that first telescope.
											It’s exciting to think about setting up your own viewing station.</p>
									</div>
								</div>
							</div>
						</div>
						<!-- single carousel item -->
						<div class="single-post-carousel">
							<div class="post-thumb">
								<img class="img-fluid" src="{% static 'img/posts/carousel/post3.jpg' %}" alt="">
							</div>
							<div class="post-details">
								<h2><a href="#">2nd Gen Smoke Alarm get up <br>
										from sleep Daily</a></h2>
								<div class="post-content d-flex justify-content-between">
									<div class="post-meta">
										<div class="thumb"><img src="{% static 'img/author/a1.png' %}" alt=""></div>
										<div class="c-desc">
											<h6>Marvel Maison</h6>
											<p><span class="lnr lnr-calendar-full"></span>13th Oct, 2018</p>
										</div>
									</div>
									<div class="details">
										<p>There is a moment in the life of any aspiring astronomer that it is time to buy that first telescope.
											It’s exciting to think about setting up your own viewing station.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Start Post Silder Area -->

	<!-- Start main body Area -->
	<div class="main-body section-gap">
		<div class="container box_1170">
			<div class="row">
				<div class="col-lg-8 post-list">
					<!-- Start Post Area -->
					<section class="post-area">
						<div class="row">
							{% for  post in posts %}
							<div class="col-lg-6 col-md-6">
								<div class="single-post-item">
									<div class="post-thumb">
										<img class="img-fluid" src="{{post.get_absolute_image_url}}" alt="">
									</div>
									<div class="post-details">
										<h4><a href="{{post.get_absolute_url}}">{{post.title}} {{some_text}}</a></h4>
										<p>{{post.description|truncatechars:20}}</p>
										<div class="blog-meta">
											<a href="#" class="m-gap"><span class="lnr lnr-calendar-full"></span>{{post.date}}</a>
											<a href="#" class="m-gap"><span class="lnr lnr-bubble"></span>05</span></a>
										</div>
									</div>
								</div>
							</div>
							{% endfor  %}

							{% include 'includes/pagination.html' %}
						</div>
					</section>
					<!-- Start Post Area -->
				</div>


				<div class="col-lg-4 sidebar">
					{% include 'includes/popular_article_author.html' %}

					{% include 'includes/popular_and_latest.html' %}

					{% include 'includes/post_categories.html' %}

					{% include 'includes/post_tags.html' %}

				</div>
			</div>
		</div>
	</div>
	<!-- Start main body Area -->


{% endblock content %}

templates/new_base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'img/fav.png' %}">
	<!-- Author Meta -->
	<meta name="author" content="codepixer">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Ruft Blog</title>

	<link href="https://fonts.googleapis.com/css?family=Roboto:400,500|Rubik:500" rel="stylesheet">
	<!--
			CSS
			============================================= -->
	<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	{{ form.media }}
</head>

<body>

    {% include 'includes/header.html' %}

    {% block content %}

    {% endblock content %}

	{% include 'includes/footer.html' %}
	


    <script src=" {% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src=" {% static 'js/vendor/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src=" {% static 'js/easing.min.js' %}"></script>
	<script src=" {% static 'js/hoverIntent.js' %}"></script>
	<script src=" {% static 'js/superfish.min.js' %}"></script>
	<script src=" {% static 'js/jquery.ajaxchimp.min.js' %}"></script>
	<script src=" {% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src=" {% static 'js/owl.carousel.min.js' %}"></script>
	<script src=" {% static 'js/jquery.tabs.min.js' %}"></script>
	<script src=" {% static 'js/jquery.nice-select.min.js' %}"></script>
	<script src=" {% static 'js/waypoints.min.js' %}"></script>
	<script src=" {% static 'js/mail-script.js' %}"></script>
	<script src=" {% static 'js/main.js' %}"></script>

		<!-- btn reply func -->
		<script>
			$('.btn-reply').click(function(){
				console.log("hello")
			  $(this).parent().parent().next('.replied-comments').fadeToggle()
			});
			
		  </script>
		<!-- end btn reply -->
</body>

</html>

templates/signup.html
{% extends 'new_base.html' %}
{% load crispy_forms_tags %}
{% block title %} Sign Up {% endblock %}


{% block content %}

<h3>Sign Up</h3>
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-row mt-100 justify-content-center" >
      <div class="form-group col-md-4 mb-0">
          {{ form.username|as_crispy_field }}
          {{ form.email|as_crispy_field }}
          {{ form.age|as_crispy_field }}
          {{ form.password1|as_crispy_field }}
          {{ form.password2|as_crispy_field }}
      </div>
    </div>
    <div class="row justify-content-center" >
    <button type="submit" class="btn btn-success  col-md-3 mb-100"> Sign up</button>
    </div>

</form>
{% endblock %}